### ISSUE TITLE
(EPIC) Replace files within an object

### ISSUE THREAD

**Issue by eporter23** [eporter23/PMtest#2]
_**As a Staff Depositor, I want to replace one or more files comprising an object, so that I can correct a mistake or provide a more preservation-friendly file format**_

**Supports features**: Digital Preservation, Versioning

**Acceptance criteria:**
Given I have adequate Hyrax user permissions to replace files in an object and to see administrative/staff-only views of a digital object
When I use the Hyrax File Manager to change out one or more files in an object
Then:

- [ ] I can see the file has changed when looking at the File Manager or Work's view
- [ ] I can add notes to a larger Preservation Versioning Workflow regarding the circumstances for why the file is being replaced
- [ ]  I can update any relevant Rights metadata regarding the circumstances for the file replacement
 - [ ] I can see the Version History for the object or file has been updated to reflect that the file was replaced, including the filename(s) involved, the username who performed the action and the time it occurred, and any notes or rights entries that have been added
 - [ ] I can verify that my detailed administrative comments do not display to end users in the front end
 - [ ] See more details https://wiki.service.emory.edu/display/DLPP/Versioning+User+Interface+Needs

**Comment by eporter23** [comment]
Acceptance criteria:
Given **I have adequate Hyrax user permissions to replace files in an object**, 
When **I use the Hyrax File Manager to change out one or more files in an object**, 
Then: 

- [ ] **I can see the file has changed when looking at the File Manager or Work's view** 
- [ ] **I can see the Version History for the object or file has been updated to reflect that the file was replaced, including the filename(s) involved, the username who performed the action and the time it occurred, and any appropriate comments**

**Comment by eporter23** [comment]
I moved this to "Backlog" in Waffle and it labeled it as such on the Issue view back in GitHub proper.

**Comment by eporter23** [comment]
This is now a Zenhub epic. It still retains various labels from all the different tool environments.
