### ISSUE TITLE
Minimal Emory branding

### ISSUE THREAD

**Issue by eporter23** [eporter23/PMtest#7]
parent of #6

As a Repository Administrator, I want to apply Emory Libraries branding and UI conventions so that I am compliant with Emory brand standards and promote a consistent user experience for DLP consumers

Acceptance criteria
- [ ] Emory Libraries logo and header from pattern library
- [ ] Emory Libraries footer from pattern library
- [ ] Emory fonts from pattern library
- [ ] Emory colors from pattern library
- [ ] See additional info for minimal branding components: https://emory.box.com/s/a42ul4tk20o9jc5zhhbuvd4gwxec6jl5

**Comment by eporter23** [comment]
I made this an epic using Waffle syntax.
